### ISSUE TITLE
Stop retrieving the packageName from the manifest

### ISSUE THREAD

**Issue by flolom** [sjcqs/gradle-konfig#6]
When upgrading to AGP 7.2.0, one of the "recommended steps" of the upgrade assistant is to "Move package from Android manifest to build files" :
> Declaration of a project's namespace using the package attribute of the Android manifest is deprecated in favour of a namespace declaration in build files.

If we proceed as recommended, it breaks the plugin with the following stacktrace
```
Caused by: java.lang.NullPointerException
	at fr.sjcqs.task.SettingsGenerationTaskKt.getPackageNameFromManifest(SettingsGenerationTask.kt:113)
	at fr.sjcqs.task.SettingsGenerationTaskKt.access$getPackageNameFromManifest(SettingsGenerationTask.kt:1)
	at fr.sjcqs.task.ConfigurationGenerationTask$Companion$create$1.execute(SettingsGenerationTask.kt:86)
	at fr.sjcqs.task.ConfigurationGenerationTask$Companion$create$1.execute(SettingsGenerationTask.kt:75)
	at org.gradle.api.internal.tasks.DefaultTaskContainer.create(DefaultTaskContainer.java:362)
	at fr.sjcqs.task.ConfigurationGenerationTask$Companion.create(SettingsGenerationTask.kt:84)
	at fr.sjcqs.konfig.KonfigPlugin$createTasks$1.execute(KonfigPlugin.kt:18)
	at fr.sjcqs.konfig.KonfigPlugin$createTasks$1.execute(KonfigPlugin.kt:10)
```

It fails because the packageName used by the plugin is extracted from the manifest. Instead, the plugin should use [the namespace attribute](https://developer.android.com/studio/build/configure-app-module#set-namespace), the same attribute used to generate `R.java` and `BuildConfig.java`

**Comment by sjcqs** [comment]
I will be busy next week but I can take a look at this after :+1:  

It requires to switch to this https://developer.android.com/studio/build/extend-agp to get the build variants's namespace so I need to dig their documentation a bit to be able to plug the `ConfigurationGenerationTask` task with their `AndroidComponentsExtension` API. 

(I set up a reminder, I'll keep you up-to-date :sweat_smile: )
